Feature branch
Oxford-G/Library pull request #1
Opened 2021-06-14 12:28 UTC by Oxford-G

Library Book Project

2021-06-14 18:53 UTC, umararshadbut requested changes
# Status: INVALID :red_circle: 

**Hi @Oxford-G **
The readme is descriptive :clap: your commit messages are perfect :clap: However there is missing the pull request description. PLease add the short description in pull request.
I am going to mark this project as invalid so when you fix the issue just submit another code review request.
##

 **If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**Umair**

2021-06-15 08:34 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work on this PR. You have fulfilled most of the requirements. Well done!
### Change(s) to make 🙅🏿 🙅🏿 🙅🏿 
- Update the getting started section of the readme. Check comment.


### Martin Afani
#### Slack: whiz25

2021-06-15 08:34 UTC, afanimartin commented on README.md
> +- `cd Library`
- How do I run the app after changing directory? Update the `Getting Started` section

2021-06-15 19:10 UTC, umararshadbut approved these changes
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @Oxford-G ! :+1: 
- Before merge please implement the toggle button funcionality.

**[OPTIONAL]** 
- [ ] Each `Book` displayed has a `button` to `toggle` the `Book` read status ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/toggle_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))
##
HAPPY CODING :computer:
**Umair**

2021-06-24 15:03 UTC, merged